[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "<Backspace>"
run  = "hidden toggle"
desc = "Toggle visibility of all files"
